/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author bruno
 */
public class Alumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form Alumno
     */
    public Alumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Alumno = new javax.swing.JLabel();
        jLabel_Documento = new javax.swing.JLabel();
        jLabel_Apellido = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Estado = new javax.swing.JLabel();
        jLabel_FechaNacimiento = new javax.swing.JLabel();
        jTextField_Documento = new javax.swing.JTextField();
        jTextField_Apellido = new javax.swing.JTextField();
        jTextField_Nombre = new javax.swing.JTextField();
        jButton_Buscar = new javax.swing.JButton();
        jButton_Nuevo = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jButton_Guardar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jRadioButton_Estado = new javax.swing.JRadioButton();

        jLabel_Alumno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Alumno.setText("Alumno");

        jLabel_Documento.setText("Documento:");

        jLabel_Apellido.setText("Apellido:");

        jLabel_Nombre.setText("Nombre:");

        jLabel_Estado.setText("Estado:");

        jLabel_FechaNacimiento.setText("Fecha de nacimiento:");

        jTextField_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DocumentoActionPerformed(evt);
            }
        });

        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jButton_Nuevo.setText("Nuevo");

        jButton_Salir.setText("Salir");

        jButton_Guardar.setText("Guardar");

        jButton_Eliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Apellido)
                    .addComponent(jLabel_Documento)
                    .addComponent(jLabel_Nombre)
                    .addComponent(jLabel_Estado)
                    .addComponent(jLabel_FechaNacimiento)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_Estado)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Apellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Documento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton_Buscar)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Nuevo)
                .addGap(18, 18, 18)
                .addComponent(jButton_Eliminar)
                .addGap(21, 21, 21)
                .addComponent(jButton_Guardar)
                .addGap(18, 18, 18)
                .addComponent(jButton_Salir)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel_Alumno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_Alumno)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Documento)
                                    .addComponent(jTextField_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_Buscar))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel_Apellido))
                            .addComponent(jTextField_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Nombre))
                        .addGap(26, 26, 26)
                        .addComponent(jRadioButton_Estado))
                    .addComponent(jLabel_Estado))
                .addGap(40, 40, 40)
                .addComponent(jLabel_FechaNacimiento)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Guardar)
                    .addComponent(jButton_Eliminar)
                    .addComponent(jButton_Nuevo)
                    .addComponent(jButton_Salir))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jTextField_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DocumentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JButton jButton_Nuevo;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel_Alumno;
    private javax.swing.JLabel jLabel_Apellido;
    private javax.swing.JLabel jLabel_Documento;
    private javax.swing.JLabel jLabel_Estado;
    private javax.swing.JLabel jLabel_FechaNacimiento;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JRadioButton jRadioButton_Estado;
    private javax.swing.JTextField jTextField_Apellido;
    private javax.swing.JTextField jTextField_Documento;
    private javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
