/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author bruno
 */
public class Inscripciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inscripciones
     */
    public Inscripciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Listado = new javax.swing.JLabel();
        jLabel_Seleccionar = new javax.swing.JLabel();
        jComboBox_Alumno = new javax.swing.JComboBox<>();
        jLabel_Formulario = new javax.swing.JLabel();
        jRadioButton_MateriasSi = new javax.swing.JRadioButton();
        jRadioButton_MateriasNo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Inscripccion = new javax.swing.JTable();
        jButton_Inscribir = new javax.swing.JButton();
        jButton_Anular = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();

        jLabel_Listado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Listado.setText("Listado de Materias");

        jLabel_Seleccionar.setText("Seleccione un alumno:");

        jComboBox_Alumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_AlumnoActionPerformed(evt);
            }
        });

        jLabel_Formulario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Formulario.setText("Formulario de Inscripción");

        jRadioButton_MateriasSi.setText("Materias inscriptas");

        jRadioButton_MateriasNo.setText("Materias no inscriptas");

        jTable_Inscripccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Inscripccion);

        jButton_Inscribir.setText("Inscribir");
        jButton_Inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InscribirActionPerformed(evt);
            }
        });

        jButton_Anular.setText("Anular inscripción");
        jButton_Anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnularActionPerformed(evt);
            }
        });

        jButton_Salir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton_MateriasSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton_MateriasNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Seleccionar)
                                .addGap(33, 33, 33)
                                .addComponent(jComboBox_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel_Listado))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel_Formulario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Inscribir)
                                .addGap(64, 64, 64)
                                .addComponent(jButton_Anular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Salir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_Formulario)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Seleccionar)
                    .addComponent(jComboBox_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel_Listado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_MateriasSi)
                    .addComponent(jRadioButton_MateriasNo))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Inscribir)
                    .addComponent(jButton_Salir)
                    .addComponent(jButton_Anular))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_AlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_AlumnoActionPerformed

    private void jButton_InscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InscribirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_InscribirActionPerformed

    private void jButton_AnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AnularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Anular;
    private javax.swing.JButton jButton_Inscribir;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JComboBox<String> jComboBox_Alumno;
    private javax.swing.JLabel jLabel_Formulario;
    private javax.swing.JLabel jLabel_Listado;
    private javax.swing.JLabel jLabel_Seleccionar;
    private javax.swing.JRadioButton jRadioButton_MateriasNo;
    private javax.swing.JRadioButton jRadioButton_MateriasSi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Inscripccion;
    // End of variables declaration//GEN-END:variables
}
